### ISSUE TITLE
500 Error when delivering notification that profiles application/ld+json

### ISSUE THREAD

**Issue by gobengo** [csarven/ldn-tests#15]
I get a 500 response from the following request, where I'd expect either a 2xx (201) or a 415 (Media Type Not Supported)

($body is http://localhost:8080/activities/4d72c129-38c6-437c-9166-2a6a0fb72162.json)

```
ben@bengo-air ~ $ echo "$body" | curl -XPOST -d @- https://linkedresearch.org/ldn/tests/inbox/ -H "Content-Type: application/ld+json; profile="https://www.w3.org/ns/activitystreams#"" -v
*   Trying 128.199.36.58...

* Connected to linkedresearch.org (128.199.36.58) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: linkedresearch.org
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> POST /ldn/tests/inbox/ HTTP/1.1
> Host: linkedresearch.org
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/ld+json; profile=https://www.w3.org/ns/activitystreams#
> Content-Length: 777
> 
* upload completely sent off: 777 out of 777 bytes
< HTTP/1.1 500 Internal Server Error
< Date: Sat, 31 Dec 2016 12:29:29 GMT
< Server: Apache/2.4.18 (Ubuntu)
< X-Powered-By: https://github.com/csarven/mayktso
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: GET, HEAD, OPTIONS, POST
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Content-Length, Content-Type, If-None-Match, Link, Location, Origin, Slug, X-Requested-With
< Access-Control-Expose-Headers: Accept-Post, Access-Control-Allow-Headers, Access-Control-Allow-Methods, Access-Control-Allow-Origin, Allow, Content-Length, Content-Type, ETag, Last-Modified, Link, Updates-Via, Vary
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 1221
< Connection: close
< 
TypeError: invalid parameter format<br> &nbsp; &nbsp;at Object.parse (/var/www/linkedresearch.org/ldn/tests/node_modules/content-type/index.js:160:11)<br> &nbsp; &nbsp;at postContainer (/var/www/linkedresearch.org/ldn/tests/node_modules/mayktso/index.js:872:31)<br> &nbsp; &nbsp;at handleResource (/var/www/linkedresearch.org/ldn/tests/node_modules/mayktso/index.js:686:14)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/www/linkedresearch.org/ldn/tests/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/var/www/linkedresearch.org/ldn/tests/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/var/www/linkedresearch.org/ldn/tests/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/www/linkedresearch.org/ldn/tests/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /var/www/linkedresearch.org/ldn/tests/node_modules/express/lib/router/index.js:277:22<br> &nbsp; &nbsp;at param (/var/www/linkedresearch.org/ldn/tests/node_modules/express/lib/router/index.js:349:14)<br> &nbsp; &nbsp;at param (/var/www/linkedresearch.org/ldn/tests/node_modules/express/lib/router/index.js:365:14)
* Closing connection 0
```

It works fine if I don't use the profile media type param. I would just stop using it, but I'm trying to implement ActivityPub too, which has [sections](https://w3c.github.io/activitypub/#client-to-server-interactions) that say I MUST use that profile param (though it's not that specific about "inbox delivery" requests specticially).

```
ben@bengo-air ~ $ echo "$body" | curl -XPOST -d @- https://linkedresearch.org/ldn/tests/inbox/ -H "Content-Type: application/ld+json" -v
*   Trying 128.199.36.58...
* Connected to linkedresearch.org (128.199.36.58) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: linkedresearch.org
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> POST /ldn/tests/inbox/ HTTP/1.1
> Host: linkedresearch.org
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/ld+json
> Content-Length: 777
> 
* upload completely sent off: 777 out of 777 bytes
< HTTP/1.1 201 Created
< Date: Sat, 31 Dec 2016 12:18:51 GMT
< Server: Apache/2.4.18 (Ubuntu)
< X-Powered-By: https://github.com/csarven/mayktso
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: GET, HEAD, OPTIONS, POST
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Content-Length, Content-Type, If-None-Match, Link, Location, Origin, Slug, X-Requested-With
< Access-Control-Expose-Headers: Accept-Post, Access-Control-Allow-Headers, Access-Control-Allow-Methods, Access-Control-Allow-Origin, Allow, Content-Length, Content-Type, ETag, Last-Modified, Link, Updates-Via, Vary
< Location: https://linkedresearch.org/ldn/tests/inbox/4a0956a0-cf53-11e6-9565-3de12904d1c5
< Link: <http://www.w3.org/ns/ldp#Resource>; rel="type", <http://www.w3.org/ns/ldp#RDFSource>; rel="type"
< Content-Length: 0
< 
* Connection #0 to host linkedresearch.org left intact
`

**Comment by csarven** [comment]
I can't access that localhost payload ;)

Can you try:
`'Content-Type: application/ld+json; profile="https://www.w3.org/ns/activitystreams#"'`

note the single quote around (instead of double as you currently have it)

**Comment by gobengo** [comment]
This is the second time I've made that mistake. Thank you for helping me.
